name: Tests

on:
  push:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependecies
        run: pod install --repo-update

      - name: Test
        run: xcodebuild test -workspace cirillo.xcworkspace -scheme cirillo -sdk=macos